name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Установить JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Шаг 3: Дать права на выполнение gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Шаг 4: Запустить сборку и анализ Sonar
      - name: Build and analyze with Sonar
        run: ./gradlew build sonar --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}