steps:
  - uses: actions/checkout@v4

  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'

  - name: Verify Gradle Wrapper
    run: |
      if [ ! -f "gradlew" ]; then
        echo "Error: gradlew not found! Generate it locally and commit."
        exit 1
      fi
      chmod +x gradlew

  - name: Build with Gradle
    run: ./gradlew build sonar --info